title: 地球科學相關筆記
description: http://gsnote.github.io 整理與地球科學相關筆記 (僅供參考)
theme: jekyll-theme-cayman
is_project_page: 
    repository_url: https://gsnote.github.io/
    repository_name: GSnote
    owner_url: https://sean0921.github.io
    owner_name: sean0921
